Read the changelog

diff --git a/targets/gentoo/snapshot/type/dead b/targets/gentoo/snapshot/type/dead
--- a/targets/gentoo/snapshot/type/dead
+++ b/targets/gentoo/snapshot/type/dead
@@ -1,11 +1,13 @@
 [section steps]
 
 create: [
-if [ "$[snapshot/source/type]" = "git" ]
-then
-	git archive --prefix=portage/ "$[snapshot/source/branch:lax]" > $tarout || die "Couldn't create tar archive"
+if [[ "$[snapshot/source/type]" == "git" ]]; then
+	git archive --prefix=portage/ "$[snapshot/source/branch:lax]" > ${tarout} || die "Couldn't create tar archive"
 else
-	rsync -a --delete --exclude /packages/ --exclude /distfiles/ --exclude /local/ --exclude CVS/ --exclude /.git/ "$[snapshot/source/remote:lax]/" "$[path/work]/portage/" || die "Couldn't sync portage tree"
-	tar -c -C $[path/work] portage > $tarout || die "Couldn't create tar archive"
+	rsync -a --delete --exclude /packages/ --exclude /distfiles/ --exclude /local/ --exclude CVS/ \
+	--exclude /.git/ "$[snapshot/source/remote:lax]/" "$[path/work]/portage/" \
+	|| die "Couldn't sync portage tree"
+
+	tar -c -C $[path/work] portage > ${tarout} || die "Couldn't create tar archive"
 fi
 ]
diff --git a/targets/gentoo/snapshot/type/live b/targets/gentoo/snapshot/type/live
--- a/targets/gentoo/snapshot/type/live
+++ b/targets/gentoo/snapshot/type/live
@@ -1,8 +1,7 @@
 [section steps]
 
 create: [
-if [ "$[snapshot/source/type]" = "git" ]
-then
+if [[ "$[snapshot/source/type]" == "git" ]]; then
 	cp -a $[path/cache/git]/$[snapshot/source/name] $[path/work]/portage
 
 	# This rebuilds the git repo with built-in git gzip compression turned off.
@@ -15,8 +14,8 @@ then
 	( cd $[path/work]/portage; git config core.compression 0 )
 	( cd $[path/work]/portage; git gc --aggressive )
 	
-	tar -c -C $[path/work] portage > $tarout || die "Couldn't create tar archive"
+	tar -c -C $[path/work] portage > ${tarout} || die "Couldn't create tar archive"
 else
-	die "snapshot/type: live is only supported for snapshot/source/type: git"
+	die "[Metro] snapshot/type: live is only supported for snapshot/source/type: git"
 fi
 ]
