rename section git to snapshot/source for consistency

diff --git a/targets/gentoo/snapshot/source/git b/targets/gentoo/snapshot/source/git
--- a/targets/gentoo/snapshot/source/git
+++ b/targets/gentoo/snapshot/source/git
@@ -4,32 +4,32 @@ sync: [
 
 ! [ -d "$[path/cache/git]" ] && install -d "$[path/cache/git]"
 
-if ! [ -e "$[path/cache/git]/$[git/name]" ]
+if ! [ -e "$[path/cache/git]/$[snapshot/source/name]" ]
 then
 	# create repo if it doesn't exist
-	git clone $[git/remote] $[path/cache/git]/$[git/name] || die "Couldn't clone git repo"
+	git clone $[snapshot/source/remote] $[path/cache/git]/$[snapshot/source/name] || die "Couldn't clone git repo"
 fi
 
-cd $[path/cache/git]/$[git/name] || die "Couldn't change directories to git repo"
+cd $[path/cache/git]/$[snapshot/source/name] || die "Couldn't change directories to git repo"
 
-branch=`git rev-parse --symbolic --branches | grep "^$[git/branch]"`
-if [ "$branch" != "$[git/branch]" ]
+branch=`git rev-parse --symbolic --branches | grep "^$[snapshot/source/branch]"`
+if [ "$branch" != "$[snapshot/source/branch]" ]
 then
 	# create local branch since it doesn't exist yet
-	git checkout --track -b $[git/branch] origin/$[git/branch] || die "Couldn't create local git branch"
+	git checkout --track -b $[snapshot/source/branch] origin/$[snapshot/source/branch] || die "Couldn't create local git branch"
 else
 	# otherwise, make sure the branch is active (so we can pull if necessary)
-	git checkout $[git/branch] || die "Couldn't checkout local git branch"
+	git checkout $[snapshot/source/branch] || die "Couldn't checkout local git branch"
 fi
 
-options="$[git/options]"
+options="$[snapshot/source/options]"
 if [ "${options/pull/}" != "${options}" ]
 then
 	echo "Performing git pull..."
-	# if we have the "pull" option in git/options, then make sure we're up-to-date
+	# if we have the "pull" option in snapshot/source/options, then make sure we're up-to-date
 	git pull > /dev/null || die "Couldn't perform git pull"
 fi
 
-git checkout $[git/branch/tar] || die "couldn't check out branch $[git/branch/tar] for tarball"
+git checkout $[snapshot/source/branch/tar] || die "couldn't check out branch $[snapshot/source/branch/tar] for tarball"
 git gc || die "couldn't gc"
 ]
diff --git a/targets/gentoo/snapshot/type/dead b/targets/gentoo/snapshot/type/dead
--- a/targets/gentoo/snapshot/type/dead
+++ b/targets/gentoo/snapshot/type/dead
@@ -3,7 +3,7 @@
 create: [
 if [ "$[snapshot/source/type]" = "git" ]
 then
-	git archive --prefix=portage/ $[git/branch:lax] > $tarout || die "Couldn't create tar archive"
+	git archive --prefix=portage/ "$[snapshot/source/branch:lax]" > $tarout || die "Couldn't create tar archive"
 else
 	rsync -a --delete --exclude /packages/ --exclude /distfiles/ --exclude /local/ --exclude CVS/ --exclude /.git/ "$[rsync/path:lax]/" "$[path/work]/portage/" || die "Couldn't sync portage tree"
 	tar -c -C $[path/work] portage > $tarout || die "Couldn't create tar archive"
