Fixes for non-Funtoo, non-ego systems.

diff --git a/targets/gentoo/snapshot/source/meta-repo b/targets/gentoo/snapshot/source/meta-repo
--- a/targets/gentoo/snapshot/source/meta-repo
+++ b/targets/gentoo/snapshot/source/meta-repo
@@ -3,6 +3,21 @@
 sync: [
 
 ! [ -d "$[path/cache/git]" ] && install -d "$[path/cache/git]"
-
-ego sync --dest=$[path/cache/git] || die "couldn't do ego sync"
+if [ -e /usr/sbin/ego ]; then 
+	ego sync --dest=$[path/cache/git] || die "couldn't do ego sync"
+else
+	if [ ! -d $[path/cache/git]/meta-repo ]; then
+		cd $[path/cache/git]
+		git clone https://github.com/funtoo/meta-repo
+		cd meta-repo
+		git submodule init
+		git submodule update
+	else
+		cd $[path/cache/git]/meta-repo
+		git reset --hard
+		git clean -fd
+		git pull
+		git submodule update
+	fi
+fi
 ]
